DROP TABLE TB_COMMUNITY;
DROP TABLE TB_POST;
DROP TABLE TB_REFERENCEROOM;
-- 자유 게시판
CREATE TABLE TB_COMMUNITY(
    IDX NUMBER(20) NOT NULL,
    CUM_TITLE VARCHAR2(255) NOT NULL,
    CUM_CONTENTS VARCHAR2(255) NOT NULL,
    CUM_IMAGE VARCHAR2(255) NOT NULL,
    CUM_REGISTERTIME DATE NOT NULL,
    RGTR_ID VARCHAR2(64) NOT NULL,
    RGTR_DT DATE NOT NULL,
    MDFR_ID VARCHAR2(64) NOT NULL,
    MDFR_DT DATE 
);
ALTER TABLE TB_COMMUNITY
ADD CONSTRAINT TB_COMMUNITY_PK PRIMARY KEY(IDX);

--공지사항
CREATE TABLE TB_POST(
    IDX NUMBER(20) NOT NULL,
    TB_POST_ID NUMBER(20) NOT NULL,
    POST_TITLE VARCHAR2(100) NOT NULL,
    POST_CONTENT VARCHAR2(3000) NOT NULL,
    POST_WRITER  VARCHAR2(20) NOT NULL,
    POST_VIEW_CNT NUMBER(11) NOT NULL,
    POST_NOTICE_YN NUMBER(1) NOT NULL,
    POST_DELETE_YN NUMBER(1) NOT NULL,
    RGTR_ID VARCHAR2(64) NOT NULL,
    RGTR_DT DATE NOT NULL,
    MDFR_ID VARCHAR2(64) NOT NULL,
    MDFR_DT DATE
);
ALTER TABLE TB_POST
ADD CONSTRAINT TB_POST_PK PRIMARY KEY(IDX);

CREATE TABLE TB_REFERENCEROOM(
    IDX NUMBER(20) NOT NULL,
    REF_REFER_ID NUMBER(20) NOT NULL,
    REF_ORGI_FILE_NAME VARCHAR2(200) NOT NULL,
    REF_SAVE_FILE_NAME VARCHAR2(500) NOT NULL,
    REF_FILE_SIZE NUMBER(11) NOT NULL,
    REF_FILE_PATH VARCHAR(25) NOT NULL,
    REF_REGISTER_TIME DATE,
    RGTR_ID VARCHAR2(64) NOT NULL,
    RGTR_DT DATE NOT NULL,
    MDFR_ID VARCHAR2(64) NOT NULL,
    MDFR_DT DATE
);
ALTER TABLE TB_REFERENCEROOM
ADD CONSTRAINT TB_REFERENCEROOM_PK PRIMARY KEY(IDX);

-- idx 및 사번용 시퀀스
CREATE SEQUENCE TB_COMMUNITY_IDX
START WITH 1
INCREMENT BY 1;

-- idx 및 사번용 시퀀스
CREATE SEQUENCE TB_POST_IDX
START WITH 1
INCREMENT BY 1;

-- idx 및 사번용 시퀀스
CREATE SEQUENCE TB_REFERENCEROOM_IDX
START WITH 1
INCREMENT BY 1;

-- 시퀀스 초기화용
DROP SEQUENCE TB_COMMUNITY_IDX;
DROP SEQUENCE TB_POST_IDX;
DROP SEQUENCE TB_REFERENCEROOM_IDX;

-- 날짜 포맷 변경
ALTER SESSION SET NLS_DATE_FORMAT = 'yyyy-MM-dd';


--
SELECT * FROM TB_COMMUNITY;
SELECT * FROM TB_POST;
SELECT * FROM TB_REFERENCEROOM;

COMMIT;

DESC TB_COMMUNITY;
DESC TB_POST;
DESC TB_REFERENCEROOM;